name = "Tufte"
license = "MIT"
licenselink = "https://github.com/kizoo69/tufte/blob/main/LICENSE.md"
description = "A Hugo theme based on Edward Tufte's distinctive typography style."
homepage = "https://github.com/kizoo69/tufte"
demo = "https://kizoo.gitlab.io/"
tags = ["blog", "tufte", "minimal", "light", "personal"]
features = ["math", "tufte-css", "tufte", "MathJax"]
min_version = "0.128.0"

[author]
name = "김재우 (Jaewoo Kim)"
homepage = "https://kizoo.gitlab.io/"
