# Set your theme here
theme: tufte
# Remove this if your site folder is not inside the theme folder
themesDir: "../.."
# The language of your website
languageCode: en-US
# If you write Chinese, Japanese or Korean, this helps with word counting
hasCJKLanguage: true
# The url of your website
baseurl: "/"
# The title of your website (shown on all the pages)
title: "Tufte Theme Example Site"
canonifyurls: true
# Number of posts per page on the home page
paginate: 5

# Only modify the following if you know what you are doing
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    guessSyntax: true

params:
  # Subtitle of the website
  subtitle: "A Hugo theme based on Tufte CSS"
  favicon: "./favicon.ico"
  touchicon: "./touch-icon.png"
  # Dark code highlighting
  codeblocksdark: false
  # Customize the indicator for margin notes
  marginNoteInd: "âŠ•"
  # Show the "Powered by Hugo and Tufte theme."
  showPoweredBy: true
  # Site wide kill switch for date in pages
  hidedate: false
  # Site wide kill switch for post summary on home page
  showSummary: true
  # Site wide kill switch for MathJax support
  math: true
  # Use upright & sans-serif font for subtitles
  sansSubtitle: false
  # Make the page centred in screen
  centerArticle: false

taxonomies:
  category: categories
  series: series
  tag: tags

# -----------------------------------------------------------------------
# Navigation menu
# -----------------------------------------------------------------------
menu:
  nav:
    - name: Home
      weight: -110
      identifier: home
      url: /
    - name: Posts
      weight: -100
      identifier: posts
      url: /posts/
    - name: A-Book
      weight: -95
      identifier: book
      url: /a-book/
    - name: Categories
      weight: -90
      identifier: categories
      url: /categories/
    - name: About
      weight: -80
      identifier: about
      url: /about/
    - name: Source Code
      weight: -70
      identifier: github
      url: "https://github.com/kizoo69/tufte"
